# Generated by Django 3.2.6 on 2021-08-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('other', 'other'), ('Female', 'Female')], max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
