# Generated by Django 3.2.6 on 2021-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_student_faculty_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_faculty',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=6),
        ),
    ]
