# Generated by Django 3.2.6 on 2021-08-24 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0008_student_faculty_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50, null=True)),
                ('Last_name', models.CharField(max_length=50, null=True)),
                ('Father_name', models.CharField(max_length=50, null=True)),
                ('Mother_name', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('roll_no', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='student_faculty',
        ),
    ]
