# Generated by Django 3.2.6 on 2021-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210824_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_images', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('news_pdf', models.FileField(blank=True, null=True, upload_to='static/news_pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, null=True)),
                ('event_start_date', models.DateField(null=True)),
                ('event_end_date', models.DateField(null=True)),
                ('event_description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
