# Generated by Django 3.2.6 on 2021-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_image_gallery_news_gallery_upcoming_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_gallery',
            name='news_pdf',
            field=models.FileField(blank=True, null=True, upload_to='news_pdf/'),
        ),
    ]
