# Generated by Django 3.2.6 on 2021-09-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_gallery',
            name='media',
        ),
        migrations.AddField(
            model_name='image_gallery',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
