# Generated by Django 3.2.6 on 2021-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20210901_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='images',
            field=models.ImageField(blank=True, default='image_gallery/default.jpg', null=True, upload_to='image_gallery/'),
        ),
        migrations.AlterField(
            model_name='news_gallery',
            name='news_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='news_gallery/'),
        ),
    ]
