# Generated by Django 3.2.6 on 2021-09-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20210901_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upcoming_events',
            new_name='Upcoming_event',
        ),
    ]
