# Generated by Django 3.2.6 on 2021-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_rename_upcoming_events_upcoming_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_gallery',
            name='news_images',
            field=models.ImageField(blank=True, default='news_gallery/default.jpg', null=True, upload_to='news_gallery/'),
        ),
        migrations.AlterField(
            model_name='news_gallery',
            name='news_pdf',
            field=models.FileField(blank=True, default='news_pdf/default.jpg', null=True, upload_to='news_pdf/'),
        ),
    ]
