# Generated by Django 3.2.6 on 2021-09-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20210905_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_gallery',
            name='news_images',
        ),
    ]
