# Generated by Django 3.2.6 on 2021-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_news_gallery_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_gallery',
            name='news_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news_gallery',
            name='news_pdf',
            field=models.FileField(blank=True, default='news_pdf/Appraisel.pdf', null=True, upload_to='news_pdf/'),
        ),
    ]
