# Generated by Django 3.2.6 on 2021-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210913_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_gallery',
            name='news_pdf',
            field=models.FileField(blank=True, default='news_pdf/Appraisal.pdf', null=True, upload_to='news_pdf/'),
        ),
    ]
