# Generated by Django 3.2.6 on 2021-09-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_courses_syllabus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='course',
        ),
    ]
