# Generated by Django 3.2.6 on 2021-09-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20210915_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='course',
            new_name='course_name',
        ),
    ]
