# Generated by Django 3.2.6 on 2021-09-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_syllabus_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.course'),
        ),
    ]
