# Generated by Django 3.2.6 on 2021-09-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_remove_syllabus_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='syllabus',
        ),
    ]
